create_claim_subject:
  description: >
    Analyze the claim: {claim} provided and construct a subject line in {language}. This subject should
    concentrate on the main keywords and phrases most likely to retrieve accurate and relevant information.

    Steps to Follow:
    1. Employ the querido_diario_advanced_search_context_tool to gain insights into effective search strategies. This tool will help you understand how to craft a subject line that utilizes advanced search contexts to enhance the precision of the search results.
    2. Incorporate appropriate search operators to refine search results efficiently. Make strategic use of these operators to focus the search and improve the likelihood of retrieving the most pertinent information.
  expected_output: >
    A query_subject in {language}, concisely incorporating strategic
    search operators to maximize the relevancy and accuracy of information retrieval.
    The subject should reflect a comprehensive understanding of the claim and include elements to enhance search precision.


research_gazettes:
  description: >
    Utilize the query_subject created by the 'Subject creator' to gather data from gazettes using the querido_diario_fetch tool.
    
    Format your query using the following JSON structure, ensuring to fill in the relevant details:
    
    {{
    "city": "{context[city]}",
    "subject": "<Enter the `query_subject` created by the previous agent>",
    "published_since": "<Enter the {context[published_since]} in YYYY-MM-DD format>",
    "published_until": "<Enter the {context[published_until]} in YYYY-MM-DD format>",
    }}

    Note: The subject should not be changed once set. Ensure the initial subject is comprehensive and precisely targets the needed information. Reevaluation of the effectiveness of the subject can be done post-task for future improvements.
  expected_output: Provide the txt_url source. The results should be directly relevant to the subject line provided, reflecting the effectiveness of the initial query construction.

collect_gazette_relevant_data:
  description: >
    Use the `txt_url` source provided by the 'Data researcher' to collect all relevant documents from the gazette using the `gazette_search` tool.    
    Structure your query in the following JSON format, filling in all required fields:
    
    {{
    "claim": {claim}
    "url": "<Enter the txt_url source>",
    "questions": {questions},
    }}
  expected_output: >
    Gather and compile a detailed response that comprehensively addresses all pertinent gazette document data related to the {questions}.
    Ensure that each response is thorough, providing extensive and accurate information to cover all relevant aspects

cross_check_collected_data_and_claim:
  description: >
    Your task is to perform a deep and thorough analysis to derive an informed conclusion by comparing the
    collected gazette data with the specific claim provided: {claim}.
    
    Use critical thinking and analytical skills to assess the accuracy and relevance of the data in relation to the claim.

    classification: Assign one of the following labels based on your analysis:

    - Not Fact: The information lacks evidence or a factual basis.
    - Trustworthy: The information is reliable, backed by evidence or reputable sources.
    - Trustworthy, but: Generally reliable, albeit with minor inaccuracies.
    - Arguable: Subject to debate or different interpretations.
    - Misleading: Distorts the facts, causing potential misunderstandings.
    - False: Demonstrably incorrect or untrue.
    - Unsustainable: Lacks long-term viability or feasibility.
    - Exaggerated: Contains elements of truth but is overstated or embellished.
    - Unverifiable: Cannot be substantiated through reliable sources.
  expected_output: >
    Compiles a comprehensive report detailing the investigative process, key finding, and evidence that supports your conclusion
    containing all relevant data between the claim and the gazette

create_fact_checking_report:
  description: >
    Upon receiving data from the Data analyst, creates a fact-checking report.
    The report should be presented in a structured JSON format. Below is the format you are to follow:

    {{
    "classification": "Classification from the previous user, this MUST be in English",
    "summary": "A concise overview reflecting your classification",
    "questions": {questions},
    "report": "A detailed narrative of your findings and evidence",
    "verification": "A detailed description of the methods and tools used for verification",
    }}

    classification: Assign one of the following labels based on your analysis:
    - ["Not Fact", "Trustworthy", "Trustworthy, but", "Arguable", "Misleading", "False", "Unsustainable", "Exaggerated", "Unverifiable"]
  
    - summary: Provide a succinct summary that directly supports your classification,
    offering insight into your analytical reasoning.

    - report: Document a comprehensive account detailing the investigative process, key findings,
    and evidence that supports your conclusion.

    - verification: Explain the specific methodologies and tools you employed to verify the
    information, highlighting your systematic approach to substantiating the claim.

    compile your response in {language}, however the classification field must remain in English
  expected_output: >
    A comprehensive fact-checking report in {language} and structured in a JSON format